version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_KEY:
    secure: a9U4XFGlqlSIqadwjg+Yj5h5IgAnwaPUEpMORCt9qYi8RJaNQwG5Cs11p6q1GF5G
build_script:
- ps: .\build.ps1
test: on
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
